file_length: 300
function_body_length: 50
function_parameter_count: 5
line_length: 150
disabled_rules: # rule identifiers to exclude from running
 - force_cast
 - trailing_whitespace
 - todo
 - weak_delegate
 - class_delegate_protocol
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
identifier_name:
 excluded: # excluded via string array
  - id
nesting:
  type_level: 3
opt_in_rules:
    - explicit_init
    - fatal_error_message
    - force_unwrapping
    - implicit_return
    - operator_usage_whitespace
    - optional_enum_case_matching
    - overridden_super_call
    - override_in_extension
    - reduce_into
    - redundant_nil_coalescing
    - untyped_error_in_catch
    - unused_control_flow_label
    - unused_declaration
    - unused_import
