file_length: 350
function_body_length: 50
function_parameter_count: 5
line_length: 150
disabled_rules: # rule identifiers to exclude from running
 - force_cast
 - trailing_whitespace
 - todo
 - weak_delegate
 - class_delegate_protocol
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
identifier_name:
 excluded: # excluded via string array
  - id
nesting:
  type_level: 3
