default_platform(:ios)

ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "4"

platform :ios do

  	lane :tests do
  	run_tests(
     	  devices: ["iPhone 8"],
      	  scheme: "GithubJobs"
    	)
	end

	lane :lint do
	swiftlint(
	  mode: :lint,
	  output_file: "swiftlint.result.json",
	  config_file: ".swiftlint.yml",
	  raise_if_swiftlint_error: true
	)
	end

end